export const QUOTES = [
  "You're not behind. You're building a better tomorrow.",
  "Routine is the quiet force behind long-term progress.",
  "Focused effort, repeated, becomes a system that works.",
  "Follow-through today builds the person you want to be tomorrow.",
  "Small, messy action beats big, flawless plans.",
  "One more day of honest effort is one step closer.",
  "The work you do today quietly shapes long-term progress.",
  "Every small steady action adds up to something bigger.",
  "Steadiness is the quiet force behind results that last.",
  "Persistence compounds. Keep going.",
  "Quiet effort, repeated, becomes lasting habits.",
  "Discipline doesn't ask for perfect \u2014 just present.",
  "A life you're proud of is just Practice repeated, day after day.",
  "Follow-through compounds. Keep going.",
  "Small, unremarkable action beats big, perfect plans.",
  "Today's modest habit is tomorrow's strength.",
  "Commitment is the quiet force behind a system that works.",
  "Lasting habits is just Commitment repeated, day after day.",
  "Rhythm is a decision, made again and again.",
  "A streak worth keeping is just Habit repeated, day after day.",
  "Routine today builds a system that works tomorrow.",
  "Who you're becoming is just Rhythm repeated, day after day.",
  "Show up today \u2014 a life you're proud of is built one day at a time.",
  "Habit beats motivation when motivation runs out.",
  "Progress hides inside boring, ordinary days.",
  "Show up today \u2014 a system that works is built one day at a time.",
  "A system that works is just Repetition repeated, day after day.",
  "Commitment today builds a streak worth keeping tomorrow.",
  "Show up today \u2014 results that last is built one day at a time.",
  "Resolve is the quiet force behind who you're becoming.",
  "Focus doesn't ask for perfect \u2014 just present.",
  "Steadiness is the quiet force behind the person you want to be.",
  "Grit is the quiet force behind a better tomorrow.",
  "Commitment is a decision, made again and again.",
  "Dedication is the quiet force behind results that last.",
  "Do it today, even modestly. That's enough.",
  "Habit is the quiet force behind lasting habits.",
  "Patience beats motivation when motivation runs out.",
  "Show up today \u2014 a stronger you is built one day at a time.",
  "Persistence today builds a stronger you tomorrow.",
  "Every small honest action adds up to something bigger.",
  "Routine beats motivation when motivation runs out.",
  "Small, plain action beats big, ambitious plans.",
  "Show up today \u2014 momentum is built one day at a time.",
  "Trust the process \u2014 Grit always pays off.",
  "Patient effort, repeated, becomes a better version of you.",
  "The work you do today quietly shapes momentum.",
  "Practice today builds quiet confidence tomorrow.",
  "The person you want to be is just Patience repeated, day after day.",
  "Every small deliberate action adds up to something bigger.",
  "Small, modest action beats big, complicated plans.",
  "Steady effort, repeated, becomes who you're becoming.",
  "The streak isn't the point \u2014 Focus is.",
  "Patience compounds. Keep going.",
  "Commitment beats motivation when motivation runs out.",
  "Small, quiet action beats big, grand plans.",
  "A system that works is just Resolve repeated, day after day.",
  "Every small patient action adds up to something bigger.",
  "Follow-through beats motivation when motivation runs out.",
  "Modest effort, repeated, becomes a life you're proud of.",
  "Structure is a decision, made again and again.",
  "Grit doesn't ask for perfect \u2014 just present.",
  "Structure is the quiet force behind a better version of you.",
  "Intention is the quiet force behind who you're becoming.",
  "You don't need a perfect day, just a deliberate one.",
  "Effort is the quiet force behind the person you want to be.",
  "Steady effort, repeated, becomes a life you're proud of.",
  "Momentum is a decision, made again and again.",
  "The streak isn't the point \u2014 Practice is.",
  "Consistent effort, repeated, becomes quiet confidence.",
  "Patience is the quiet force behind the person you want to be.",
  "Grit compounds. Keep going.",
  "Today's deliberate habit is tomorrow's strength.",
  "Resolve compounds. Keep going.",
  "Rhythm doesn't ask for perfect \u2014 just present.",
  "Grit today builds who you're becoming tomorrow.",
  "The work you do today quietly shapes steady growth.",
  "Quiet effort, repeated, becomes momentum.",
  "Modest effort, repeated, becomes steady growth.",
  "Every small small action adds up to something bigger.",
  "Trust the process \u2014 Repetition always pays off.",
  "Do it today, even quietly. That's enough.",
  "Trust the process \u2014 Persistence always pays off.",
  "Trust the process \u2014 Effort always pays off.",
  "The work you do today quietly shapes real change.",
  "Steadiness is a decision, made again and again.",
  "Momentum beats motivation when motivation runs out.",
  "Commitment compounds. Keep going.",
  "The streak isn't the point \u2014 Follow-through is.",
  "Small, plain action beats big, grand plans.",
  "Every small modest action adds up to something bigger.",
  "You don't need a perfect day, just a steady one.",
  "The streak isn't the point \u2014 Discipline is.",
  "Progress hides inside boring, messy days.",
  "Repetition is the quiet force behind a stronger you.",
  "Today's consistent habit is tomorrow's strength.",
  "Today's steady habit is tomorrow's strength.",
  "Small, modest action beats big, idealized plans.",
  "Patient effort, repeated, becomes a better tomorrow.",
  "Show up today \u2014 who you're becoming is built one day at a time.",
  "One more day of quiet effort is one step closer.",
  "The work you do today quietly shapes a streak worth keeping.",
  "Small, small action beats big, flawless plans.",
  "One more day of simple effort is one step closer.",
  "Trust the process \u2014 Momentum always pays off.",
  "Practice beats motivation when motivation runs out.",
  "Resolve is a decision, made again and again.",
  "Show up today \u2014 a streak worth keeping is built one day at a time.",
  "Effort today builds a streak worth keeping tomorrow.",
  "Intention compounds. Keep going.",
  "The work you do today quietly shapes results that last.",
  "Rhythm is the quiet force behind the person you want to be.",
  "You're not behind. You're building real change.",
  "You're not behind. You're building a better version of you.",
  "Small steps still count as steps forward.",
  "You're not behind. You're building lasting habits.",
  "Intention beats motivation when motivation runs out.",
  "Follow-through is the quiet force behind a better tomorrow.",
  "One more day of focused effort is one step closer.",
  "You're not behind. You're building steady growth.",
  "One more day of patient effort is one step closer.",
  "Routine is a decision, made again and again.",
  "Habit today builds the person you want to be tomorrow.",
  "Focused effort, repeated, becomes a streak worth keeping.",
  "Trust the process \u2014 Intention always pays off.",
  "Routine is the quiet force behind momentum.",
  "Habit today builds a stronger you tomorrow.",
  "Small, imperfect action beats big, flawless plans.",
  "Small, plain action beats big, dramatic plans.",
  "Practice is a decision, made again and again.",
  "Focus is the quiet force behind a life you're proud of.",
  "Trust the process \u2014 Patience always pays off.",
  "Follow-through doesn't ask for perfect \u2014 just present.",
  "Progress hides inside boring, plain days.",
  "Show up today \u2014 lasting habits is built one day at a time.",
  "The streak isn't the point \u2014 Structure is.",
  "Patience doesn't ask for perfect \u2014 just present.",
  "Today's quiet habit is tomorrow's strength.",
  "A stronger you is just Routine repeated, day after day.",
  "One more day of steady effort is one step closer.",
  "Steady effort, repeated, becomes a streak worth keeping.",
  "Persistence is the quiet force behind lasting habits.",
  "Show up today \u2014 quiet confidence is built one day at a time.",
  "You don't need a perfect day, just a focused one.",
  "Quiet effort, repeated, becomes the person you want to be.",
  "Discipline is the quiet force behind a life you're proud of.",
  "You don't need a perfect day, just a small one.",
  "Follow-through today builds a better tomorrow tomorrow.",
  "The work you do today quietly shapes a stronger you.",
  "Momentum is just Habit repeated, day after day.",
  "Momentum compounds. Keep going.",
  "The streak isn't the point \u2014 Consistency is.",
  "You're not behind. You're building a stronger you.",
  "Structure beats motivation when motivation runs out.",
  "Momentum is just Effort repeated, day after day.",
  "Progress hides inside boring, small days.",
  "Practice doesn't ask for perfect \u2014 just present.",
  "Grit today builds a system that works tomorrow.",
  "Focus compounds. Keep going.",
  "Quiet effort, repeated, becomes a life you're proud of.",
  "Today's honest habit is tomorrow's strength.",
  "You're not behind. You're building who you're becoming.",
  "You're not behind. You're building momentum.",
  "Consistency compounds. Keep going.",
  "A system that works is just Effort repeated, day after day.",
  "Trust the process \u2014 Commitment always pays off.",
  "Habit is a decision, made again and again.",
  "Trust the process \u2014 Practice always pays off.",
  "Patience is the quiet force behind momentum.",
  "Small effort, repeated, becomes lasting habits.",
  "Steady effort, repeated, becomes the person you want to be.",
  "A better tomorrow is just Repetition repeated, day after day.",
  "Resolve today builds real change tomorrow.",
  "Rhythm today builds a better version of you tomorrow.",
  "The streak isn't the point \u2014 Resolve is.",
  "Grit is the quiet force behind who you're becoming.",
  "Dedication today builds a better version of you tomorrow.",
  "The streak isn't the point \u2014 Routine is.",
  "Long-term progress is just Effort repeated, day after day.",
  "Every small consistent action adds up to something bigger.",
  "Consistency beats motivation when motivation runs out.",
  "You're not behind. You're building long-term progress.",
  "The habit is the goal. Everything else follows.",
  "Results that last is just Persistence repeated, day after day.",
  "Progress hides inside boring, modest days.",
  "You don't need a perfect day, just a modest one.",
  "Dedication is a decision, made again and again.",
  "Today's focused habit is tomorrow's strength.",
  "Small, ordinary action beats big, idealized plans.",
  "Small, small action beats big, ambitious plans.",
  "Small, quiet action beats big, idealized plans.",
  "Patient effort, repeated, becomes real change.",
  "You're not behind. You're building a life you're proud of.",
  "Modest effort, repeated, becomes real change.",
  "Commitment is the quiet force behind a streak worth keeping.",
  "Small, small action beats big, idealized plans.",
  "Real change is just Follow-through repeated, day after day.",
  "Progress hides inside boring, unremarkable days.",
  "Steady growth is just Consistency repeated, day after day.",
  "One more day of small effort is one step closer.",
  "Repetition doesn't ask for perfect \u2014 just present.",
  "The work you do today quietly shapes the person you want to be.",
  "Grit beats motivation when motivation runs out.",
  "Patient effort, repeated, becomes steady growth.",
  "Practice is the quiet force behind results that last.",
  "Habit is the quiet force behind a life you're proud of.",
  "Patience is a decision, made again and again.",
  "Intention is the quiet force behind a better tomorrow.",
  "The streak isn't the point \u2014 Intention is.",
  "A better version of you is just Routine repeated, day after day.",
  "Focused effort, repeated, becomes momentum.",
  "Focus today builds a life you're proud of tomorrow.",
  "You don't need a perfect day, just a honest one.",
  "Persistence is the quiet force behind quiet confidence.",
  "Show up today \u2014 real change is built one day at a time.",
  "Trust the process \u2014 Rhythm always pays off.",
  "A life you're proud of is just Routine repeated, day after day.",
  "Small effort, repeated, becomes a stronger you.",
  "Quiet confidence is just Practice repeated, day after day.",
  "Small effort, repeated, becomes the person you want to be.",
  "Small, quiet action beats big, dramatic plans.",
  "Do it today, even unremarkablely. That's enough.",
  "Consistent effort, repeated, becomes a life you're proud of.",
  "Do it today, even imperfectly. That's enough.",
  "Steadiness is the quiet force behind momentum.",
  "Habit today builds a better version of you tomorrow.",
  "The person you want to be is just Focus repeated, day after day.",
  "Habit compounds. Keep going.",
  "Intention is a decision, made again and again.",
  "Repetition today builds momentum tomorrow.",
  "Small, ordinary action beats big, ambitious plans.",
  "The work you do today quietly shapes a system that works.",
  "Small effort, repeated, becomes momentum.",
  "Keep the promise you made to yourself today.",
  "Show up today \u2014 long-term progress is built one day at a time.",
  "Structure today builds a stronger you tomorrow.",
  "Small, imperfect action beats big, dramatic plans.",
  "Focused effort, repeated, becomes long-term progress.",
  "Patience today builds a better version of you tomorrow.",
  "Honest effort, repeated, becomes real change.",
  "Who you're becoming is just Momentum repeated, day after day.",
  "Do it today, even plainly. That's enough.",
  "The streak isn't the point \u2014 Commitment is.",
  "Today's patient habit is tomorrow's strength.",
  "Small effort, repeated, becomes results that last.",
  "Small, modest action beats big, grand plans.",
  "Honest effort, repeated, becomes lasting habits.",
  "Honest effort, repeated, becomes quiet confidence.",
  "Who you're becoming is just Resolve repeated, day after day.",
  "Rhythm beats motivation when motivation runs out.",
  "Structure compounds. Keep going.",
  "Trust the process \u2014 Focus always pays off.",
  "Routine compounds. Keep going.",
  "Every small focused action adds up to something bigger.",
  "Commitment is the quiet force behind lasting habits.",
  "Steadiness beats motivation when motivation runs out.",
  "Every small quiet action adds up to something bigger.",
  "Grit is the quiet force behind long-term progress.",
  "Resolve beats motivation when motivation runs out.",
  "Small, modest action beats big, perfect plans.",
  "Commitment doesn't ask for perfect \u2014 just present.",
  "Repetition is a decision, made again and again.",
  "Routine doesn't ask for perfect \u2014 just present.",
  "Persistence beats motivation when motivation runs out.",
  "Small, imperfect action beats big, idealized plans.",
  "Practice today builds a stronger you tomorrow.",
  "Trust the process \u2014 Routine always pays off.",
  "Discipline compounds. Keep going.",
  "Small, plain action beats big, flawless plans.",
  "Patience is the quiet force behind quiet confidence.",
  "Effort doesn't ask for perfect \u2014 just present.",
  "You don't need a perfect day, just a quiet one.",
  "Small, modest action beats big, flawless plans.",
  "The work you do today quietly shapes quiet confidence.",
  "Repetition is the quiet force behind momentum.",
  "Repetition beats motivation when motivation runs out.",
  "The work you do today quietly shapes lasting habits.",
  "Do it today, even messyly. That's enough.",
  "Consistency is a decision, made again and again.",
  "Show up today \u2014 the person you want to be is built one day at a time.",
  "Small, unremarkable action beats big, dramatic plans.",
  "You're not behind. You're building the person you want to be.",
  "The streak isn't the point \u2014 Persistence is.",
  "Grit is a decision, made again and again.",
  "Trust the process \u2014 Follow-through always pays off.",
  "Steady effort, repeated, becomes long-term progress.",
  "Who you're becoming is just Habit repeated, day after day.",
  "You're not behind. You're building quiet confidence.",
  "Persistence doesn't ask for perfect \u2014 just present.",
  "Small, messy action beats big, ambitious plans.",
  "Repetition compounds. Keep going.",
  "Steadiness compounds. Keep going.",
  "Structure doesn't ask for perfect \u2014 just present.",
  "Trust the process \u2014 Steadiness always pays off.",
  "Do it today, even ordinaryly. That's enough.",
  "One more day of deliberate effort is one step closer.",
  "Today's small habit is tomorrow's strength.",
  "One more day of modest effort is one step closer.",
  "Practice compounds. Keep going.",
  "Resolve today builds a stronger you tomorrow.",
  "Small, modest action beats big, dramatic plans.",
  "You're not behind. You're building results that last.",
  "Small, ordinary action beats big, grand plans.",
  "Progress hides inside boring, imperfect days.",
  "Simple effort, repeated, becomes who you're becoming.",
  "Structure today builds results that last tomorrow.",
  "Steadiness doesn't ask for perfect \u2014 just present.",
  "Intention doesn't ask for perfect \u2014 just present.",
  "You already know what to do. Go do it.",
  "The streak isn't the point \u2014 Momentum is.",
  "Discipline beats motivation when motivation runs out.",
  "The streak isn't the point \u2014 Dedication is.",
  "Effort is the quiet force behind a stronger you.",
  "Rhythm compounds. Keep going.",
  "Habit is the quiet force behind the person you want to be.",
  "Who you're becoming is just Follow-through repeated, day after day.",
  "The work you do today quietly shapes a better tomorrow.",
  "Every checkmark today is a vote for who you're becoming.",
  "Habit doesn't ask for perfect \u2014 just present.",
  "The streak isn't the point \u2014 Habit is.",
  "Practice today builds a better version of you tomorrow.",
  "The streak isn't the point \u2014 Repetition is.",
  "Every small simple action adds up to something bigger.",
  "The person you want to be is just Habit repeated, day after day.",
  "Focused effort, repeated, becomes quiet confidence.",
  "You don't need a perfect day, just a simple one.",
  "Persistence is a decision, made again and again.",
  "Focus today builds real change tomorrow.",
  "The streak isn't the point \u2014 Grit is.",
  "Consistent effort, repeated, becomes results that last.",
  "Long-term progress is just Grit repeated, day after day.",
  "Dedication doesn't ask for perfect \u2014 just present.",
  "Show up today \u2014 a better version of you is built one day at a time.",
  "The work you do today quietly shapes a life you're proud of.",
  "The streak isn't the point \u2014 Steadiness is.",
  "Deliberate effort, repeated, becomes the person you want to be.",
  "You're not behind. You're building a system that works.",
  "Trust the process \u2014 Consistency always pays off.",
  "Trust the process \u2014 Dedication always pays off.",
  "Long-term progress is just Patience repeated, day after day.",
  "Focus beats motivation when motivation runs out.",
  "The streak isn't the point \u2014 Patience is.",
  "Deliberate effort, repeated, becomes results that last.",
  "Simple effort, repeated, becomes real change.",
  "The streak isn't the point \u2014 Effort is.",
  "Effort compounds. Keep going.",
  "One more day of consistent effort is one step closer.",
  "Discipline is a decision, made again and again.",
  "Show up today \u2014 steady growth is built one day at a time.",
  "Small effort, repeated, becomes quiet confidence.",
  "Do it today, even smallly. That's enough.",
  "Consistency doesn't ask for perfect \u2014 just present.",
  "Intention today builds lasting habits tomorrow.",
  "Steadiness today builds a stronger you tomorrow.",
  "Deliberate effort, repeated, becomes a stronger you.",
  "The work you do today quietly shapes a better version of you.",
  "Results that last is just Follow-through repeated, day after day.",
  "Effort is a decision, made again and again.",
  "The person you want to be is just Discipline repeated, day after day.",
  "Discipline is the quiet force behind who you're becoming.",
  "Dedication beats motivation when motivation runs out.",
  "Trust the process \u2014 Resolve always pays off.",
  "Show up today \u2014 a better tomorrow is built one day at a time.",
  "Follow-through is a decision, made again and again.",
  "Progress hides inside boring, quiet days.",
];
